name: Build Angular with SonarQube

on:
    pull_request:
    push:
      branches:
        - main

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
